export const questionsRawData = [
  [
    "Mã câu",
    "Phần",
    "ID",
    "Nhóm đánh giá",
    "Câu hỏi hiển thị",
    "Hướng dẫn/Giải thích",
    "Loại trả lời",
    "Đáp án 0",
    "Đáp án 1",
    "Đáp án 2",
    "Đáp án 3",
    "Đáp án 4",
    "Đáp án 5",
    "Đáp án 6",
    "Đáp án 7",
    "Đáp án 8",
    "Đáp án 9",
    "Đáp án 10",
    "Đáp án 11",
    "Đáp án 12",
    "Trọng số",
    "Bắt buộc",
    "Ghi chú triển khai",
  ],
  [
    "PHẦN A: THÔNG TIN NHÀ MÁY",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "A01",
    "A - Bối cảnh",
    "FI01",
    "Thông tin nhà máy",
    "Tên doanh nghiệp/nhà máy là gì?",
    "Nhập tên pháp lý hoặc tên thường dùng của nhà máy.",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A02",
    "A - Bối cảnh",
    "FI02",
    "Thông tin nhà máy",
    "Nhà máy đặt tại tỉnh/thành phố nào?",
    "Nhập địa điểm vận hành chính.",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A03",
    "A - Bối cảnh",
    "FI03",
    "Thông tin nhà máy",
    "Ngành sản xuất chính của nhà máy là gì?",
    "Chọn 1 phương án",
    "Danh sách",
    "Gỗ / nội thất",
    "Cơ khí / kim loại",
    "May mặc / da giày",
    "Nhựa / cao su",
    "Thực phẩm / đồ uống",
    "Điện tử / điện lạnh",
    "Vật liệu xây dựng",
    "Bao bì / in ấn",
    "Khác",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A04",
    "A - Bối cảnh",
    "FI04",
    "Thông tin nhà máy",
    "Sản phẩm hoặc nhóm sản phẩm chính là gì?",
    "",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A05",
    "A - Bối cảnh",
    "FI04b",
    "Thông tin nhà máy",
    "Nhà máy của anh/chị đã hoạt động được bao nhiêu năm?",
    "",
    "Điền số",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A06",
    "A - Bối cảnh",
    "FI05",
    "Thông tin nhà máy",
    "Số lao động trực tiếp của nhà máy?",
    "",
    "Điền số",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A07",
    "A - Bối cảnh",
    "FI06",
    "Thông tin nhà máy",
    "Số lao động hỗ trợ tại hiện trường (cấp liệu, QC chuyền, sửa máy, tổ trưởng không  trực tiếp sản xuất...)?",
    "Ví dụ: Cấp liệu, QC chuyền, sửa máy, tổ trưởng không  trực tiếp sản xuất…",
    "Điền số",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A08",
    "A - Bối cảnh",
    "FI07",
    "Thông tin nhà máy",
    "Số lao động quản lý, văn phòng.",
    "",
    "Điền số",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A09",
    "A - Bối cảnh",
    "FI08",
    "Thông tin nhà máy",
    "Nhà máy đang vận hành bao nhiêu ca sản xuất mỗi ngày?",
    "Chọn 1 phương án",
    "Danh sách",
    "1 ca",
    "2 ca",
    "3 ca",
    "Khác",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "A10",
    "A - Bối cảnh",
    "FI09",
    "Thông tin nhà máy",
    "Nhà máy hiện đang sử dụng những hệ thống hoặc phần mềm nào trong quản lý và sản xuất?",
    "Có thể chọn nhiều lựa chọn.",
    "Nhiều lựa chọn",
    "Excel / Google Sheet",
    "Phần mềm kế toán kiêm quản lý kho",
    "Phần mềm ERP / MES / phần mềm sản xuất",
    "Appsheet",
    "Phần mềm khác",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Không",
    "Không tính điểm",
  ],
  [
    "PHẦN B: KHÁM 8 LÃNG PHÍ",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "B01",
    "B - Triệu chứng",
    "W01",
    "Lỗi và làm lại",
    "Tỷ lệ sản phẩm lỗi của nhà máy đang ở mức nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B02",
    "B - Triệu chứng",
    "W01",
    "Lỗi và làm lại",
    "Lỗi chất lượng có thường xuyên lặp lại không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B03",
    "B - Triệu chứng",
    "W02",
    "Sản xuất thừa",
    "Nhà máy sản xuất thừa nhiều hàng thành phẩm không?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B04",
    "B - Triệu chứng",
    "W02",
    "Sản xuất thừa",
    "Nhà máy sản xuất thừa nhiều hàng bán thành phẩm không?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B05",
    "B - Triệu chứng",
    "W03",
    "Chờ đợi",
    "Trong quá trình sản xuất, có phải thường xuyên phải chờ đợi (vật tư, máy móc, công đoạn trước, QC hoặc hướng dẫn...) trước khi có thể tiếp tục công việc?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B06",
    "B - Triệu chứng",
    "W03",
    "Chờ đợi",
    "Việc chờ đợi làm giảm năng suất và ảnh hưởng đến khả năng hoàn thành kế hoạch sản xuất như thế nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B07",
    "B - Triệu chứng",
    "W04",
    "Không khai thác hết nguồn lực",
    "Nhà máy có đang khai thác hiệu quả nguồn nhân lực hiện có?",
    "",
    "Thang điểm 0-4",
    "0 - Rất hiệu quả",
    "1 - Hiệu quả",
    "2 - Trung bình",
    "3 - Không hiệu quả",
    "4 - Rất không hiệu quả",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B08",
    "B - Triệu chứng",
    "W04",
    "Không khai thác hết nguồn lực",
    "Nhà máy có đang khai thác hiệu quả nguồn máy móc thiết bị hiện có?",
    "",
    "Thang điểm 0-4",
    "0 - Rất hiệu quả",
    "1 - Hiệu quả",
    "2 - Trung bình",
    "3 - Không hiệu quả",
    "4 - Rất không hiệu quả",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B09",
    "B - Triệu chứng",
    "W05",
    "Vận chuyển",
    "Tình trạng nguyên vật liệu, bán thành phẩm hoặc thành phẩm phải vận chuyển nhiều lần hoặc đi quãng đường xa không cần thiết xảy ra với tần suất như thế nào?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B10",
    "B - Triệu chứng",
    "W05",
    "Vận chuyển",
    "Tình trạng vận chuyển không cần thiết gây ảnh hưởng đến lãng phí thời gian, giảm năng suất ở mức độ nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B11",
    "B - Triệu chứng",
    "W06",
    "Tồn kho",
    "Tình trạng nguyên vật liệu, bán thành phẩm hoặc thành phẩm tồn vượt nhu cầu, tồn lâu hoặc chậm luân chuyển xảy ra với tần suất như thế nào?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B12",
    "B - Triệu chứng",
    "W06",
    "Tồn kho",
    "Tình trạng tồn kho dư thừa hoặc chậm luân chuyển gây ảnh hưởng đến vốn, diện tích lưu trữ, chất lượng hoặc khả năng kiểm soát sản xuất ở mức độ nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B13",
    "B - Triệu chứng",
    "W07",
    "Thao tác thừa",
    "Tình trạng người lao động phải đi lại, tìm kiếm, cúi, với, xoay người hoặc thực hiện các thao tác không cần thiết xảy ra với tần suất như thế nào?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B14",
    "B - Triệu chứng",
    "W07",
    "Thao tác thừa",
    "Các thao tác thừa gây ảnh hưởng đến năng suất, thời gian thực hiện công việc hoặc sức khỏe người lao động ở mức độ nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B15",
    "B - Triệu chứng",
    "W08",
    "Quy trình thừa",
    "Tình trạng công việc phải thực hiện thêm các bước xử lý, kiểm tra, phê duyệt, ghi chép hoặc nhập liệu không cần thiết xảy ra với tần suất như thế nào?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "B16",
    "B - Triệu chứng",
    "W08",
    "Quy trình thừa",
    "Các bước công việc không cần thiết gây ảnh hưởng đến thời gian xử lý, chi phí, tiến độ hoặc hiệu quả công việc ở mức độ nào?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "PHẦN C: KHÁM 8 DẤU HIỆU BẤT THƯỜNG TẠI HIỆN TRƯỜNG",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C01",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS01",
    "Kế hoạch bất ổn",
    "Kế hoạch sản xuất có bị thay đổi sau khi đã phát hành không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C02",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS02",
    "Kế hoạch bất ổn",
    "Có phát sinh đơn hàng chen ngang làm thay đổi thứ tự sản xuất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C03",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS03",
    "Kế hoạch bất ổn",
    "Các bộ phận có thường xuyên không thống nhất về thứ tự ưu tiên sản xuất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C04",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS04",
    "Thiếu nguồn lực",
    "Có xảy ra tình trạng thiếu vật tư tại điểm sử dụng làm ảnh hưởng đến sản xuất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C05",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS05",
    "Thiếu nguồn lực",
    "Có xảy ra tình trạng thiếu nhân lực so với kế hoạch sản xuất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C06",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS06",
    "Thiếu nguồn lực",
    "Máy móc hoặc thiết bị có phải dừng do hỏng hóc ngoài kế hoạch không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C07",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS07",
    "Dòng chảy sản xuất gián đoạn",
    "Có công đoạn thường xuyên trở thành nút thắt của dây chuyền không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không xảy ra",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C08",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS08",
    "Dòng chảy sản xuất gián đoạn",
    "Có nhiều bán thành phẩm tồn giữa các công đoạn không?",
    "",
    "Thang điểm 0-4",
    "0 - Rất thấp",
    "1 - Thấp",
    "2 - Trung bình",
    "3 - Cao",
    "4 - Rất cao",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C09",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS09",
    "Dòng chảy sản xuất gián đoạn",
    "Các công đoạn có phải chờ nhau để tiếp tục sản xuất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C10",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS10",
    "Thông tin và phối hợp không thông suốt",
    "Thông tin thay đổi có được truyền đạt chậm đến người thực hiện không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C11",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS11",
    "Thông tin và phối hợp không thông suốt",
    "Có xảy ra tình trạng các bộ phận sử dụng thông tin hoặc dữ liệu không thống nhất không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C12",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS12",
    "Thông tin và phối hợp không thông suốt",
    "Có phải xác nhận hoặc hỏi lại thông tin nhiều lần trước khi thực hiện công việc không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C13",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS13",
    "Tiêu chuẩn và cách làm không thống nhất",
    "Cùng một công việc nhưng mỗi người thực hiện theo một cách khác nhau không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C14",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS14",
    "Tiêu chuẩn và cách làm không thống nhất",
    "Hướng dẫn công việc (SOP/WI) có thiếu hoặc không được cập nhật khi quy trình thay đổi không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C15",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS15",
    "Tiêu chuẩn và cách làm không thống nhất",
    "Nhân viên mới có gặp khó khăn khi làm việc chỉ dựa trên tài liệu hướng dẫn hiện có không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C16",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS16",
    "Quản trị hiện trường mang tính chữa cháy",
    "Quản lý có phải dành phần lớn thời gian để xử lý sự cố phát sinh hằng ngày không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C17",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS17",
    "Quản trị hiện trường mang tính chữa cháy",
    "Có nhiều vấn đề đã xử lý nhưng tiếp tục lặp lại không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C18",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS18",
    "Quản trị hiện trường mang tính chữa cháy",
    "Sau các cuộc họp, nhiều hành động không được thực hiện đúng thời hạn không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C19",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS19",
    "Dữ liệu và quyết định thiếu tin cậy",
    "Các số liệu giữa các bộ phận có thường xuyên không khớp nhau không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C20",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS20",
    "Dữ liệu và quyết định thiếu tin cậy",
    "Có mất nhiều thời gian để tổng hợp dữ liệu phục vụ quản lý không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C21",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS21",
    "Dữ liệu và quyết định thiếu tin cậy",
    "Các quyết định sản xuất có chủ yếu dựa trên kinh nghiệm thay vì dữ liệu không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C22",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS22",
    "Cải tiến không được duy trì",
    "Các ý tưởng cải tiến có thường xuyên không được triển khai hoặc phản hồi không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C23",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS23",
    "Cải tiến không được duy trì",
    "Sau khi triển khai cải tiến, tình trạng cũ có quay trở lại không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "C24",
    "C - Dấu hiệu bất thường tại hiện trường",
    "AS24",
    "Cải tiến không được duy trì",
    "Các tiêu chuẩn mới có không được duy trì hoặc kiểm tra định kỳ không?",
    "",
    "Thang điểm 0-4",
    "0 - Gần như không bao giờ",
    "1 - Hiếm khi",
    "2 - Thỉnh thoảng",
    "3 - Thường xuyên",
    "4 - Rất thường xuyên",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "1",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "PHẦN D: KHÁM 11 MODULE INVAMAX FOS",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "D01",
    "D - Hệ thống",
    "MD01",
    "Core",
    "Mục tiêu chiến lược và mục tiêu vận hành của nhà máy được xác định rõ ràng.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D02",
    "D - Hệ thống",
    "MD01",
    "Core",
    "Vai trò và trách nhiệm của từng cấp quản lý được xác định rõ ràng và thực hiện nhất quán.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D03",
    "D - Hệ thống",
    "MD01",
    "Core",
    "Các quyết định điều hành được đưa ra kịp thời và dựa trên mục tiêu chung của doanh nghiệp.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D04",
    "D - Hệ thống",
    "MD02",
    "People",
    "Mỗi vị trí công việc đều có yêu cầu về năng lực và trách nhiệm được xác định rõ.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D05",
    "D - Hệ thống",
    "MD02",
    "People",
    "Nhân viên được đào tạo và hướng dẫn đầy đủ để đáp ứng yêu cầu công việc.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D06",
    "D - Hệ thống",
    "MD02",
    "People",
    "Việc đánh giá, phát triển và kế thừa năng lực được thực hiện thường xuyên và hiệu quả.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D07",
    "D - Hệ thống",
    "MD03",
    "Flow",
    "Các quy trình vận hành chính và mối liên kết giữa các bộ phận được thiết kế rõ ràng, thống nhất và phù hợp với thực tế nhà máy.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D08",
    "D - Hệ thống",
    "MD03",
    "Flow",
    "Công việc, thông tin, quyết định, vật tư và sản phẩm được luân chuyển đúng quy trình, đúng thời điểm và không bị gián đoạn không cần thiết.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D09",
    "D - Hệ thống",
    "MD03",
    "Flow",
    "Các điểm gián đoạn, tắc nghẽn hoặc bất hợp lý trong dòng chảy được phát hiện, xử lý và theo dõi hiệu quả.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D10",
    "D - Hệ thống",
    "MD04",
    "Standard",
    "Các công việc quan trọng đều có tiêu chuẩn hoặc hướng dẫn thực hiện rõ ràng.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D11",
    "D - Hệ thống",
    "MD04",
    "Standard",
    "Các tiêu chuẩn được nhân viên tuân thủ trong quá trình làm việc.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D12",
    "D - Hệ thống",
    "MD04",
    "Standard",
    "Các tiêu chuẩn được cập nhật và cải tiến khi có thay đổi hoặc phát sinh vấn đề.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D13",
    "D - Hệ thống",
    "MD05",
    "Capacity",
    "Kế hoạch sản xuất được lập dựa trên năng lực thực tế của nhà máy.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D14",
    "D - Hệ thống",
    "MD05",
    "Capacity",
    "Năng lực của máy móc, nhân lực và thiết bị được theo dõi và cân đối thường xuyên.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D15",
    "D - Hệ thống",
    "MD05",
    "Capacity",
    "Nhà máy chủ động điều chỉnh năng lực để đáp ứng kịp thời sự thay đổi của nhu cầu sản xuất.",
    "",
    "Thang điểm 0-4",
    "0 - Đã thiết lập đầy đủ, được triển khai nhất quán và phát huy hiệu quả trong thực tế",
    "1 - Đã thiết lập đầy đủ và được triển khai khá tốt, còn một số điểm cần hoàn thiện",
    "2 - Đã thiết lập nhưng việc triển khai chưa đồng đều hoặc hiệu quả chưa ổn định",
    "3 - Đã thiết lập một phần hoặc việc triển khai còn mang tính hình thức",
    "4 - Hầu như chưa thiết lập hoặc chưa triển khai",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D16",
    "D - Hệ thống",
    "MD06",
    "Daily Management",
    "Hoạt động điều hành hằng ngày được thực hiện theo quy trình thống nhất.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D17",
    "D - Hệ thống",
    "MD06",
    "Daily Management",
    "Các vấn đề phát sinh được giao trách nhiệm, theo dõi và xử lý đến khi hoàn thành.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D18",
    "D - Hệ thống",
    "MD06",
    "Daily Management",
    "Hoạt động họp điều hành hằng ngày giúp phát hiện bất thường, thống nhất hành động và xử lý vấn đề kịp thời.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D19",
    "D - Hệ thống",
    "MD07",
    "Quality",
    "Chất lượng được kiểm soát ngay tại từng công đoạn sản xuất.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D20",
    "D - Hệ thống",
    "MD07",
    "Quality",
    "Các lỗi phát sinh được phân tích nguyên nhân và có biện pháp ngăn ngừa tái diễn.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D21",
    "D - Hệ thống",
    "MD07",
    "Quality",
    "Hiệu lực của các hành động khắc phục và phòng ngừa được kiểm tra sau khi triển khai.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D22",
    "D - Hệ thống",
    "MD08",
    "Knowledge",
    "Các kinh nghiệm và bài học sau khi giải quyết vấn đề được ghi nhận và chia sẻ để áp dụng lại.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D23",
    "D - Hệ thống",
    "MD08",
    "Knowledge",
    "Các cơ chế ghi chép, chia sẻ và chuyển giao tri thức được áp dụng để giảm sự phụ thuộc vào kinh nghiệm của từng cá nhân.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D24",
    "D - Hệ thống",
    "MD08",
    "Knowledge",
    "Tri thức của tổ chức được cập nhật và sử dụng để nâng cao hiệu quả làm việc.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D25",
    "D - Hệ thống",
    "MD09",
    "Digital",
    "Việc thu thập và quản lý dữ liệu được áp dụng đầy đủ để cung cấp thông tin chính xác, kịp thời cho quản lý.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D26",
    "D - Hệ thống",
    "MD09",
    "Digital",
    "Thông tin được chia sẻ hiệu quả giữa các bộ phận thông qua các công cụ số.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D27",
    "D - Hệ thống",
    "MD09",
    "Digital",
    "Các phần mềm hoặc công cụ số đang hỗ trợ giảm công việc thủ công và cung cấp dữ liệu kịp thời cho quản lý.",
    "",
    "Thang điểm 0-4",
    "0 - Được áp dụng rộng rãi, hỗ trợ hiệu quả cho vận hành",
    "1 - Được áp dụng khá tốt",
    "2 - Đã áp dụng nhưng hiệu quả chưa ổn định",
    "3 - Mới áp dụng một phần hoặc còn hạn chế",
    "4 - Hầu như chưa áp dụng",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D28",
    "D - Hệ thống",
    "MD10",
    "Kaizen",
    "Các ý tưởng cải tiến được khuyến khích, ghi nhận và triển khai thường xuyên.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D29",
    "D - Hệ thống",
    "MD10",
    "Kaizen",
    "Các hoạt động cải tiến được theo dõi và đánh giá kết quả một cách hệ thống.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D30",
    "D - Hệ thống",
    "MD10",
    "Kaizen",
    "Các cải tiến hiệu quả được tiêu chuẩn hóa và nhân rộng trong toàn nhà máy.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D31",
    "D - Hệ thống",
    "MD11",
    "Sustain",
    "Các tiêu chuẩn và kết quả cải tiến được duy trì thông qua hoạt động kiểm tra định kỳ.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D32",
    "D - Hệ thống",
    "MD11",
    "Sustain",
    "Các vấn đề được phát hiện và xử lý chủ động trước khi trở thành sự cố nghiêm trọng.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "3",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "D33",
    "D - Hệ thống",
    "MD11",
    "Sustain",
    "Văn hóa tuân thủ tiêu chuẩn và cải tiến liên tục được duy trì trong toàn nhà máy.",
    "",
    "Thang điểm 0-4",
    "0 - Thực hiện rất hiệu quả và tạo kết quả rõ ràng",
    "1 - Thực hiện tốt, còn một số điểm cần cải thiện",
    "2 - Thực hiện ở mức trung bình",
    "3 - Thực hiện chưa hiệu quả hoặc thiếu nhất quán",
    "4 - Hầu như chưa thực hiện",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "2",
    "Có",
    "Điểm càng cao càng nghiêm trọng",
  ],
  [
    "PHẦN E: MỤC TIÊU ƯU TIÊN CỦA DOANH NGHIỆP",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "E01",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Trong 12 tháng tới, doanh nghiệp muốn ưu tiên đạt được những kết quả nào?",
    "",
    "Chọn tối đa 3 phương án.",
    "Tăng doanh thu hoặc mở rộng thị trường",
    "Tăng năng suất",
    "Giảm chi phí sản xuất",
    "Cải thiện chất lượng",
    "Giao hàng đúng hạn",
    "Giảm tồn kho",
    "Giảm thời gian sản xuất",
    "Giảm phụ thuộc vào cá nhân",
    "Chuẩn hóa hệ thống quản trị",
    "Nâng cao năng lực đội ngũ",
    "Số hóa dữ liệu và báo cáo",
    "Mở rộng công suất",
    "Khác",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E02",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Nếu chỉ được chọn một mục tiêu để tập trung trong 6 tháng tới, anh/chị sẽ chọn mục tiêu nào?",
    "",
    "Chọn một phương án.",
    "Tăng doanh thu hoặc mở rộng thị trường",
    "Tăng năng suất",
    "Giảm chi phí sản xuất",
    "Cải thiện chất lượng",
    "Giao hàng đúng hạn",
    "Giảm tồn kho",
    "Giảm thời gian sản xuất",
    "Giảm phụ thuộc vào cá nhân",
    "Chuẩn hóa hệ thống quản trị",
    "Nâng cao năng lực đội ngũ",
    "Số hóa dữ liệu và báo cáo",
    "Mở rộng công suất",
    "Khác",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E03",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Theo anh/chị, đâu là ba yếu tố lớn nhất đang cản trở doanh nghiệp đạt được mục tiêu?",
    "",
    "Chọn tối đa 3 phương án.",
    "Thị trường và đơn hàng",
    "Nguồn vốn đầu tư",
    "Máy móc, thiết bị",
    "Nhân lực và đội ngũ quản lý",
    "Quy trình và hệ thống quản trị",
    "Kế hoạch và tổ chức sản xuất",
    "Chất lượng sản phẩm",
    "Dữ liệu và thông tin quản lý",
    "Sự phối hợp giữa các bộ phận",
    "Khác:",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E04",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Theo anh/chị, đâu là trở ngại lớn nhất đang cản trở doanh nghiệp đạt được mục tiêu? Vì sao?",
    "",
    "Văn bản, giới hạn khoảng 300 ký tự",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E05",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Doanh nghiệp muốn ưu tiên bắt đầu cải thiện từ khu vực nào?",
    "",
    "Chọn tối đa 3 phương án.",
    "Mục tiêu, cơ chế điều hành và phân quyền",
    "Năng lực đội ngũ và tổ chức nhân sự",
    "Quy trình vận hành và phối hợp giữa các bộ phận",
    "Tiêu chuẩn và hướng dẫn công việc",
    "Kế hoạch, năng lực và điều độ sản xuất",
    "Quản trị hiện trường hằng ngày",
    "Kiểm soát và cải tiến chất lượng",
    "Quản lý tài liệu và tri thức",
    "Dữ liệu và số hóa",
    "Cải tiến liên tục",
    "Duy trì tiêu chuẩn và văn hóa",
    "Chưa xác định, cần được tư vấn",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E06",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Doanh nghiệp hiện có thể bố trí nguồn lực ở mức nào cho hoạt động cải tiến?",
    "",
    "Chọn một phương án.",
    "Có thể bố trí người phụ trách, thời gian và ngân sách phù hợp",
    "Có thể bố trí người phụ trách và thời gian, nhưng ngân sách còn hạn chế",
    "Có thể triển khai thử nghiệm ở một khu vực nhỏ",
    "Có mong muốn cải tiến nhưng chưa bố trí được người phụ trách",
    "Hiện chưa thể bố trí nguồn lực",
    "Chưa xác định, cần đánh giá thêm",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "E07",
    "E - Mục tiêu ưu tiên của doanh nghiệp",
    "",
    "",
    "Sau khi nhận báo cáo, anh/chị mong muốn bước tiếp theo là gì?",
    "",
    "Chọn một phương án.",
    "Tự nghiên cứu và triển khai theo khuyến nghị",
    "Trao đổi online để làm rõ kết quả",
    "Mời chuyên gia khảo sát trực tiếp tại nhà máy",
    "Xây dựng lộ trình cải tiến 30–60–90 ngày",
    "Triển khai thử nghiệm tại một khu vực",
    "Tìm giải pháp máy móc, thiết bị hoặc công cụ hỗ trợ",
    "Chưa có kế hoạch, chỉ muốn tham khảo kết quả",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "PHẦN F: NHẬN KẾT QUẢ KHÁM BỆNH",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "",
    "Anh/chị đã hoàn thành khảo sát. Vui lòng xác nhận thông tin dưới đây để hệ thống gửi Báo cáo Khám bệnh Nhà máy và các khuyến nghị phù hợp với doanh nghiệp của anh/chị.",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
  ],
  [
    "F01",
    "F - Thông tin nhận kết quả khám bệnh",
    "PI01",
    "",
    "Họ và tên",
    "",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "F02",
    "F - Thông tin nhận kết quả khám bệnh",
    "PI02",
    "",
    "Chức vụ",
    "",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "F03",
    "F - Thông tin nhận kết quả khám bệnh",
    "PI03",
    "",
    "Email nhận báo cáo",
    "",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "F04",
    "F - Thông tin nhận kết quả khám bệnh",
    "PI04",
    "",
    "Số điện thoại",
    "",
    "Văn bản",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
  [
    "F05",
    "F - Thông tin nhận kết quả khám bệnh",
    "PI05",
    "",
    "Check box: Tôi đồng ý để INVAMAX sử dụng thông tin trên nhằm gửi báo cáo, tư vấn và các thông tin liên quan đến chương trình Khám bệnh Nhà máy.",
    "",
    "Check box",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "",
    "0",
    "Có",
    "Không tính điểm",
  ],
]
